apiVersion: v1
kind: Service
metadata:
  name: cinsevennia
spec:
  ports:
  - name: port1
    port: 4000
    targetPort: 4000
  - name: port2
    port: 4001
    targetPort: 4001
  - name: port3
    port: 4005
    targetPort: 4005
  - name: db
    port: 5432
    targetPort: 5432
  selector:
    run: cinsevennia
  type: LoadBalancer
