version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    command: python /code/manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "80:80"
    links:
      - web:web
